import { History } from './types'

export const users: Array<{ name: string; address: string }> = [
  { name: 'A test user', address: 'San Fransico, CA' },
  { name: 'a test user', address: 'San Fransico, CA' },
  { name: 'a test user', address: 'San Fransico, CA' },
  { name: 'a test user', address: 'San Fransico, CA' },
  { name: 'b test user', address: 'San Fransico, CA' },
  { name: 'B test user', address: 'San Fransico, CA' },
  { name: 'b test user', address: 'San Fransico, CA' },
  { name: 'd test user', address: 'San Fransico, CA' },
  { name: 'da test user', address: 'San Fransico, CA' },
  { name: 'Da test user', address: 'San Fransico, CA' },
  { name: 'c test user', address: 'San Fransico, CA' },
  { name: 'z test user', address: 'San Fransico, CA' },
  { name: 'D test user', address: 'San Fransico, CA' },
  { name: 'S test user', address: 'San Fransico, CA' },
  { name: 's test user', address: 'San Fransico, CA' },
  { name: 'W test user', address: 'San Fransico, CA' },
  { name: 'a test user', address: 'San Fransico, CA' },
  { name: 'w test user', address: 'San Fransico, CA' },
  { name: 'na test user', address: 'San Fransico, CA' },
  { name: 'ya test user', address: 'San Fransico, CA' },
  { name: 'ya test user', address: 'San Fransico, CA' },
  { name: 'ea test user', address: 'San Fransico, CA' },
  { name: 'ma test user', address: 'San Fransico, CA' },
  { name: 'ja test user', address: 'San Fransico, CA' },
  { name: 'ia test user', address: 'San Fransico, CA' },
  { name: 'ca test user', address: 'San Fransico, CA' },
  { name: 'qa test user', address: 'San Fransico, CA' },
  { name: 'a test user', address: 'San Fransico, CA' },
]

export const history: Array<History> = [
  {
    from: '@jacob_shamberger',
    to: '@thomas_schulz',
    amount: 99.99,
    coin: 'btc',
  },
  {
    from: '@jacob_shamberger',
    to: '@thomas_schulz',
    amount: 89.99,
    coin: 'eth',
  },
  {
    from: '@jacob_shamberger',
    to: '@thomas_schulz',
    amount: 94.99,
    coin: 'ltc',
  },
  {
    from: '@jacob_shamberger',
    to: '@thomas_schulz',
    amount: 19.99,
    coin: 'bnb',
  },
  {
    from: '@jacob_shamberger',
    to: '@thomas_schulz',
    amount: 23.99,
    coin: 'btc',
  },
  {
    from: '@thomas_schulz',
    to: '@jacob_shamberger',
    amount: 99.99,
    coin: 'btc',
  },
  {
    from: '@thomas_schulz',
    to: '@jacob_shamberger',
    amount: 99.99,
    coin: 'eth',
  },
  {
    from: '@thomas_schulz',
    to: '@jacob_shamberger',
    amount: 56.99,
    coin: 'btc',
  },
]
